### ISSUE TITLE
Not logged in message

### ISSUE THREAD

**Issue by ochorocho** [marketing-factory/oauth2#1]
![bildschirmfoto 2018-07-12 um 08 54 48](https://user-images.githubusercontent.com/4623070/42617287-77739144-85b1-11e8-96ca-043cded86ba7.png)

TYPO3 Configuration
![bildschirmfoto 2018-07-12 um 08 52 22](https://user-images.githubusercontent.com/4623070/42617292-796529fe-85b1-11e8-9585-29871ed55f46.png)

Gitlab Application config
![bildschirmfoto 2018-07-12 um 08 57 05](https://user-images.githubusercontent.com/4623070/42617361-b5bbb2d8-85b1-11e8-9cc7-b8e99fc51e43.png)

It seems to work but TYPO3 ist still complaining that the login failed.
But on Gitlab i'm logged in after all.

I couldn't find any details in the logs.
Do you have any hint for me to either fix this issue or get more debuggin information?

Thanks for your help

**Comment by tehplague** [comment]
You did not specify the correct repository name - the group is missing. Thus, TYPO3 cannot tell whether your user is permitted to access the Git repository or not, since it just won't find it.
Please fix the repository name and make sure that you are using the latest extension release since there happened to be some minor quirks you otherwise might run into as well.

**Comment by ochorocho** [comment]
@tehplague repository name includes the namespace right?

Thanks, will test when back home this evening.

**Comment by tehplague** [comment]
Yes, either the group name if it belongs to one or the user's username who created the repo.

**Comment by ochorocho** [comment]
Changed the gitlab.gitlabRepositoryName e.g. namespace/group-name and it just worked.  :-)
